import streamlit as st, pandas as pd, numpy as np
st.set_page_config(layout='wide',page_title='Retail Dashboard')
st.title('📊 Retail Forecasting & Inventory Dashboard')
df=pd.read_csv('data/retail_sales.csv')
df['date']=pd.to_datetime(df['date'])
store=st.sidebar.selectbox('Store',sorted(df.store_id.unique()))
item=st.sidebar.selectbox('Item',sorted(df.item_id.unique()))
sub=df[(df.store_id==store)&(df.item_id==item)]
c1,c2,c3,c4=st.columns(4)
c1.metric('Total Sales', int(sub.qty_sold.sum()))
c2.metric('Avg Sales', round(sub.qty_sold.mean(),1))
c3.metric('Peak Sales', int(sub.qty_sold.max()))
c4.metric('Promo Days', int(sub.promo_flag.sum()))
st.subheader('Sales Trend')
st.line_chart(sub.set_index('date')['qty_sold'])
st.subheader('Monthly Sales')
m=sub.groupby(sub.date.dt.to_period('M'))['qty_sold'].sum()
m.index=m.index.astype(str)
st.bar_chart(m)
st.subheader('Recommendation')
avg=sub.qty_sold.tail(30).mean()
std=sub.qty_sold.tail(30).std()
lead=int(sub.lead_time_days.iloc[-1])
ss=1.65*std*np.sqrt(lead)
rop=avg*lead+ss
order=max(0,int(round(rop-60)))
st.table(pd.DataFrame({'Metric':['Safety Stock','ROP','Order Qty'],'Value':[round(ss,2),round(rop,2),order]}))
st.success('Recruiter-ready portfolio dashboard')
